DEBUG = True

DIALECT = 'mysql'
DRIVER='pymysql'
USERNAME = 'root'
PASSWORD = 'sMx141110~'
HOST = '127.0.0.1'
PORT = 3306
DATABASE = 'testforwindows'

#dialect+driver://root:1q2w3e4r5t@127.0.0.1:3306/dbname?charset=UTF8MB4
SQLALCHEMY_DATABASE_URI = "{}+{}://{}:{}@{}:{}/{}?charset=UTF8MB4".format(DIALECT,DRIVER,USERNAME,PASSWORD,HOST,PORT,DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = False
print(SQLALCHEMY_DATABASE_URI)